steps:
# 1. Construir a Imagem Docker (usa o Dockerfile)
- name: 'gcr.io/cloud-builders/docker'
  args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/architect-prime-backend:$COMMIT_SHA',
      '.'
    ]
  id: Build

# 2. Enviar a imagem para o Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/architect-prime-backend:$COMMIT_SHA'
    ]
  id: Push

# 3. Fazer o Deploy no Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
      'run',
      'deploy',
      'architect-prime-backend', # Nome do serviço Cloud Run
      '--image',
      'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/architect-prime-backend:$COMMIT_SHA',
      '--region',
      'us-central1', # Região do Cloud Run
      '--allow-unauthenticated', # Permite acesso público para testes
      '--platform',
      'managed'
    ]
  id: Deploy
